import gradio as gr
from func import *

args = normal.get_args()
llm_instance = run(args)

def main():
    """
    Main function to launch the Gradio interface for the Data Agent application.
    This function sets up a Gradio interface with multiple components including:
    - Markdown for the title
    - File upload for data files
    - DataFrame for displaying processed data
    - Gallery for displaying plots of the data
    - Chatbot for generating final reports
    - Textboxes for SQL statements and user questions
    - Buttons for clearing history and submitting queries
    The interface is styled with custom CSS and a theme, and it handles file uploads,
    user interactions, and displays the results accordingly.
    Components:
    - gr.Markdown: Displays the title "Data Agent"
    - gr.Files: Allows users to upload data files
    - gr.DataFrame: Displays the processed data
    - gr.Gallery: Shows plots of the data
    - gr.Chatbot: Displays the final report
    - gr.Textbox: For SQL statements and user questions
    - gr.Button: For clearing history and submitting queries
    Event Handlers:
    - file_output.upload: Processes the uploaded file and updates the DataFrame
    - sumbit.click: Handles user queries and updates the chatbot, gallery, and DataFrame
    - clear_history.click: Clears the session and resets the interface components
    The interface is launched with a queue and specific configurations for threading and height.
    """
    with gr.Blocks(css="footer {visibility: hidden}",theme=gr.themes.Soft()) as demo:
        gr.Markdown("""<center><font size=10>Data Agent</center>""")
        with gr.Row(equal_height=False):
            file_output = gr.Files(height=200)
            df_process = gr.DataFrame(scale=1, height=350,interactive=False,wrap=True)
        with gr.Row(equal_height=False):
            
            df = gr.outputs.Dataframe(type='pandas')
            gallery = gr.Gallery(label="plots of the data",preview = False).style(height='auto',columns=2)
        with gr.Row(equal_height=False):
                chatbot = gr.Chatbot(label='final report',scale=1)
                with gr.Column():
                    textbox_out = gr.Textbox(lines=3, label='SQL statement generated by llms')
                    textbox = gr.Textbox(lines=3, label='send your question about the data')
                    with gr.Row():
                        clear_history = gr.Button("🧹 clear")
                        sumbit = gr.Button("🚀 submit")
        file_output.upload(llm_instance.process_file, inputs= [file_output],outputs=[df_process])
        sumbit.click(llm_instance.model_chat, [textbox, chatbot, df_process], [textbox_out, chatbot, gallery, df])
        clear_history.click(fn=normal.clear_session,
                            inputs=[],
                            outputs=[textbox, textbox_out, chatbot, gallery, df, df_process])
    demo.queue(api_open=False).launch(max_threads=10, height=800, share=False)
if __name__ == "__main__":
    main()